version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pip install uv
      - uv pip compile pyproject.toml -o docs/requirements.txt
    install:
      - pip install -r docs/requirements.txt

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
