[pytest]
filterwarnings =
    ignore:.*disp.*iprint.*deprecated.*:DeprecationWarning:sklearn.linear_model._logistic
    ignore::sklearn.exceptions.ConvergenceWarning
    ignore::pytest.PytestUnraisableExceptionWarning
