"""
Unit tests for the ConcatDataSetSuite class, which handles concatenating
multi-method prediction datasets generated by ClassifyAllSuite into a single
wide-format dataset.
"""

import os
import unittest
from pathlib import Path

import polars as pl

from dmqclib.classify.step7_concat_datasets.dataset_suite import ConcatDataSetSuite
from dmqclib.common.config.classify_config import ClassificationConfig
from dmqclib.classify.step6_classify_dataset.dataset_all_suite import ClassifyAllSuite
from dmqclib.common.loader.classify_loader import (
    load_classify_step1_input_dataset,
    load_classify_step2_summary_dataset,
    load_classify_step3_select_dataset,
    load_classify_step4_locate_dataset,
    load_classify_step5_extract_dataset,
)


class TestConcatDataSetSuite(unittest.TestCase):
    """
    A suite of tests for the ConcatDataSetSuite class, ensuring proper pivoting
    and concatenation of multi-method prediction datasets.
    """

    def setUp(self):
        """
        Set up test environment by loading necessary configuration and preparing
        data through the entire pipeline up to ClassifyAllSuite.
        """
        self.config_file_path = str(
            Path(__file__).resolve().parent
            / "data"
            / "config"
            / "test_classify_001.yaml"
        )
        self.config = ClassificationConfig(str(self.config_file_path))
        self.config.select("NRT_BO_001")

        # Configure to use the ModelSuite with two methods for testing
        self.config.data["step_class_set"]["steps"]["concat"] = "ConcatDataSetSuite"
        self.config.data["step_class_set"]["steps"]["classify"] = "ClassifyAllSuite"
        self.config.data["step_class_set"]["steps"]["model"] = "ModelSuite"
        self.config.data["step_param_set"]["steps"]["model"] = {
            "methods": ["XGB", "DT"]
        }

        model_path = Path(__file__).resolve().parent / "data" / "training"

        # Map composite keys to existing test models to allow `read_models` to succeed.
        self.model_file_names = {
            "xgb_temp": str(model_path / "model_temp_xgb.joblib"),
            "dt_temp": str(model_path / "model_temp_dt.joblib"),
            "xgb_psal": str(model_path / "model_psal_xgb.joblib"),
            "dt_psal": str(model_path / "model_psal_dt.joblib"),
            "xgb_pres": str(model_path / "model_pres_xgb.joblib"),
            "dt_pres": str(model_path / "model_pres_dt.joblib"),
        }

        self.test_data_file = str(
            Path(__file__).resolve().parent
            / "data"
            / "input"
            / "nrt_cora_bo_test.parquet"
        )

        # --- Run pipeline up to Classification ---
        self.ds_input = load_classify_step1_input_dataset(self.config)
        self.ds_input.input_file_name = str(self.test_data_file)
        self.ds_input.read_input_data()

        self.ds_summary = load_classify_step2_summary_dataset(
            self.config, input_data=self.ds_input.input_data
        )
        self.ds_summary.calculate_stats()

        self.ds_select = load_classify_step3_select_dataset(
            self.config, input_data=self.ds_input.input_data
        )
        self.ds_select.label_profiles()

        self.ds_locate = load_classify_step4_locate_dataset(
            self.config,
            input_data=self.ds_input.input_data,
            selected_profiles=self.ds_select.selected_profiles,
        )
        self.ds_locate.process_targets()

        self.ds_extract = load_classify_step5_extract_dataset(
            self.config,
            input_data=self.ds_input.input_data,
            selected_profiles=self.ds_select.selected_profiles,
            selected_rows=self.ds_locate.selected_rows,
            summary_stats=self.ds_summary.summary_stats,
        )
        self.ds_extract.process_targets()

        # Run ClassifyAllSuite to generate long-format multi-method predictions
        self.ds_classify = ClassifyAllSuite(
            self.config, test_sets=self.ds_extract.target_features
        )
        self.ds_classify.model_file_names = self.model_file_names
        self.ds_classify.read_models()
        self.ds_classify.test_targets()

    def test_step_name(self):
        """Check that the ConcatDataSetSuite step name is correctly assigned."""
        ds = ConcatDataSetSuite(self.config)
        self.assertEqual(ds.step_name, "concat")

    def test_output_file_names(self):
        """Verify that the default output file name for merged predictions is as expected."""
        ds = ConcatDataSetSuite(self.config)

        self.assertEqual(
            "/path/to/concat_1/nrt_bo_001/concat_folder_1/predictions.parquet",
            str(ds.output_file_name),
        )

    def test_test_sets(self):
        """
        Check that input data and suite predictions are correctly loaded into
        ConcatDataSetSuite. Due to multiple methods, prediction row count should
        be a multiple of the input row count.
        """
        ds = ConcatDataSetSuite(
            self.config,
            input_data=self.ds_input.input_data,
            predictions=self.ds_classify.predictions,
        )

        # Base input data is 19480 rows
        self.assertIsInstance(ds.input_data, pl.DataFrame)
        self.assertEqual(ds.input_data.shape[0], 19480)
        self.assertEqual(ds.input_data.shape[1], 30)

        # Predictions have 2 methods (XGB, DT), so 19480 * 2 = 38960 rows
        # Columns: method, row_id, platform_code, profile_no, observation_no, label, class, score
        self.assertIsInstance(ds.predictions["temp"], pl.DataFrame)
        self.assertEqual(ds.predictions["temp"].shape[0], 38960)
        self.assertEqual(ds.predictions["temp"].shape[1], 8)
        self.assertIn("method", ds.predictions["temp"].columns)

    def test_merge_predictions(self):
        """
        Confirm that merge_predictions correctly pivots the 'method' column
        and joins everything into a single wide DataFrame.
        """
        ds = ConcatDataSetSuite(
            self.config,
            input_data=self.ds_input.input_data,
            predictions=self.ds_classify.predictions,
        )
        ds.merge_predictions()

        self.assertIsInstance(ds.merged_predictions, pl.DataFrame)

        # Row count should match the original input data
        self.assertEqual(ds.merged_predictions.shape[0], 19480)

        # Check that specific wide-format columns were created
        expected_columns = [
            "temp_label", "xgb_temp_predicted", "xgb_temp_score", "dt_temp_predicted",
            "dt_temp_score",
            "psal_label", "xgb_psal_predicted", "xgb_psal_score", "dt_psal_predicted",
            "dt_psal_score",
            "pres_label", "xgb_pres_predicted", "xgb_pres_score", "dt_pres_predicted",
            "dt_pres_score",
        ]

        for col in expected_columns:
            self.assertIn(col, ds.merged_predictions.columns)

        # Original 30 cols + 3 targets * (1 label + 2 methods * 2 cols(predicted, score)) = 30 + 3 * 5 = 45 cols
        self.assertEqual(ds.merged_predictions.shape[1], 45)

    def test_merge_predictions_with_empty_input(self):
        """
        Check that a ValueError is raised if the input data for merging is absent.
        """
        ds = ConcatDataSetSuite(
            self.config,
            input_data=None,
            predictions=self.ds_classify.predictions,
        )
        with self.assertRaises(ValueError):
            ds.merge_predictions()

    def test_merge_predictions_with_empty_predictions(self):
        """
        Check that a ValueError is raised if the predictions for merging are absent.
        """
        ds = ConcatDataSetSuite(
            self.config,
            input_data=self.ds_input.input_data,
            predictions=None,
        )
        with self.assertRaises(ValueError):
            ds.merge_predictions()

    def test_write_predictions(self):
        """
        Check that the merged wide-format predictions are correctly written to a
        Parquet file and that the file exists afterwards.
        """
        ds = ConcatDataSetSuite(
            self.config,
            input_data=self.ds_input.input_data,
            predictions=self.ds_classify.predictions,
        )

        data_path = Path(__file__).resolve().parent / "data" / "classify"
        ds.output_file_name = str(data_path / "temp_predictions_suite.parquet")

        ds.merge_predictions()
        ds.write_merged_predictions()

        self.assertTrue(os.path.exists(ds.output_file_name))

        os.remove(ds.output_file_name)

    def test_write_no_results(self):
        """
        Ensure ValueError is raised if write_merged_predictions is called
        before predictions have been merged.
        """
        ds = ConcatDataSetSuite(
            self.config,
            input_data=self.ds_input.input_data,
            predictions=self.ds_classify.predictions,
        )

        with self.assertRaises(ValueError):
            ds.write_merged_predictions()
