path_info:
  input:
    base_path: /path/to/data
    folder_name: input
  select:
    base_path: /path/to/data
    folder_name: select
  locate:
    base_path: /path/to/data
    folder_name: select
  extract:
    base_path: /path/to/data
    folder_name: select

NRT_BO_001:
  input:
    base_class: InputDataSetA
    file_name: nrt_cora_bo_test.parquet
  select:
    base_class: SelectDataSetA
    folder_name: nrt_bo_001
    file_name: selected_profiles.parquet
  locate:
    base_class: LocateDataSetA
    folder_name: nrt_bo_001
    targets:
      temp:
        file_name: temp_rows.parquet
        variable: temp_qc
      psal:
        file_name: psal_rows.parquet
        variable: psal_qc
  extract:
    base_class: ExtractDataSetA
    folder_name: nrt_bo_001
    targets:
      temp:
        file_name: temp_features.parquet
        variable: temp_qc
      psal:
        file_name: psal_features.parquet
        variable: psal_qc
