path_info:
  common:
    base_path: /path/to/data
  input:
    base_path: /path/to/data

target_set1: &target_set1
  targets:
    temp:
      variable: temp_qc
    psal:
      variable: psal_qc

feature_set1: &feature_set1
  features:
    - {class: location,
       scales: {longitude: {min: 0, max: 1},
                latitude: {min: 0, max: 1}}}
    - {class: day_of_year, convert: sine}
    - {class: profile_summary_stats5,
       scales: {mean: {min: 0, max: 1},
                median: {min: 0, max: 1},
                sd: {min: 0, max: 1},
                p25: {min: 0, max: 1},
                p75: {min: 0, max: 1}}}
    - {class: basic_values3_plus_flanks,
       flank_up: 5,
       flank_down: 0,
       scales: {temp: {min: 0, max: 1},
                psal: {min: 0, max: 1},
                pres: {min: 0, max: 1}}}

NRT_BO_001:
  common:
    folder_name: nrt_bo_001
  input:
    file_name: nrt_cora_bo_test.parquet
  base_class:
    input: InputDataSetA
    summary: SummaryDataSetA
    select: SelectDataSetA
    locate: LocateDataSetA
    extract: ExtractDataSetA
  <<: *target_set1
  extract:
    <<: *feature_set1
