path_info:
  input:
    base_path: /path/to/data
    folder_name: input
  select:
    base_path: /path/to/data
    folder_name: select

NRT_BO_001:
  input:
    base_class: InputDataSetA
    file_name: nrt_cora_bo_test.parquet
  select:
    base_class: SelectDataSetA
    folder_name: nrt_bo_001
    file_name: selected_profiles.parquet

NRT_BO_002:
  input:
    base_class: InputDataSetA
  select:
    base_class: SelectDataSetA
