path_info:
  common:
    base_path: /path/to/data
  input:
    base_path: /path/to/data

NRT_BO_001:
  common:
    folder_name: nrt_bo_001
  input:
    file_name: nrt_cora_bo_test.parquet
  base_class:
    input: InputDataSetA
    select: SelectDataSetA
    locate: LocateDataSetA
    extract: ExtractDataSetA
  select:
    file_name: selected_profiles.parquet
  locate:
    targets:
      temp:
        file_name: temp_rows.parquet
        variable: temp_qc
      psal:
        file_name: psal_rows.parquet
        variable: psal_qc
  extract:
    targets:
      temp:
        file_name: temp_features.parquet
        variable: temp_qc
      psal:
        file_name: psal_features.parquet
        variable: psal_qc
