path_info:
  input:
    base_path: /path/to/data
    folder_name: input
  select:
    base_path: /path/to/data
    folder_name: select
  locate:
    base_path: /path/to/data
    folder_name: select

NRT_BO_001:
  input:
    base_class: InputDataSetA
    file_name: nrt_cora_bo_test.parquet
  select:
    base_class: SelectDataSetA
    folder_name: nrt_bo_001
    file_name: selected_profiles.parquet
  locate:
    base_class: LocateDataSetA
    folder_name: nrt_bo_001
    targets:
      temp:
        file_name: temp_positions.parquet
        variable: temp_qc
      psal:
        file_name: psal_positions.parquet
        variable: psal_qc

NRT_BO_002:
  input:
    base_class: InputDataSetA
  select:
    base_class: SelectDataSetA
  locate:
    base_class: LocateDataSetA
    targets:
      temp:
        variable: temp_qc
