path_info:
  common:
    base_path: /path/to/data
  input:
    base_path: /path/to/data

targets: &default_targets
  targets:
    temp:
      variable: temp_qc
    psal:
      variable: psal_qc

NRT_BO_001:
  common:
    folder_name: nrt_bo_001
  input:
    file_name: nrt_cora_bo_test.parquet
  base_class:
    input: InputDataSetA
    select: SelectDataSetA
    locate: LocateDataSetA
    extract: ExtractDataSetA
  locate: *default_targets
  extract: *default_targets
