path_info:
  input:
    base_path: /path/to/data
    folder_name: input
  train:
    base_path: /path/to/data
    folder_name: train

NRT_BO_001:
  input:
    base_class: DataSetA
    file_name: nrt_cora_bo_test.parquet
  train:
    folder_name: nrt_bo_001
    base_class: TrainingSetA


NRT_BO_002:
  input:
    base_class: DataSetA
